import "./globals.css";
import { SessionProvider } from 'next-auth/react'
import { auth } from '../../auth';

import { quicksand } from "./font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body className={quicksand.className}>{children}</body>
    </html>
    </SessionProvider>
  );
}
